### ISSUE TITLE
http://192.168.1.205/authorize.php?response_type=code&client_id=testclient&state=xyz

### ISSUE THREAD

**Issue by zengzhi88** [bshaffer/oauth2-server-php#1059]
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'code_challenge' in 'field list' in /var/www/html/oauth2-server-php/src/OAuth2/Storage/Pdo.php:292 Stack trace: #0 /var/www/html/oauth2-server-php/src/OAuth2/Storage/Pdo.php(292): PDOStatement->execute() #1 [internal function]: OAuth2\Storage\Pdo->setAuthorizationCodeWithIdToken() #2 /var/www/html/oauth2-server-php/src/OAuth2/Storage/Pdo.php(254): call_user_func_array() #3 /var/www/html/oauth2-server-php/src/OAuth2/ResponseType/AuthorizationCode.php(59): OAuth2\Storage\Pdo->setAuthorizationCode() #4 /var/www/html/oauth2-server-php/src/OAuth2/ResponseType/AuthorizationCode.php(31): OAuth2\ResponseType\AuthorizationCode->createAuthorizationCode() #5 /var/www/html/oauth2-server-php/src/OAuth2/Controller/AuthorizeController.php(140): OAuth2\ResponseType\AuthorizationCode->getAuthorizeResponse() #6 /var/www/html/oauth2-server-php/src/OAuth2/Server.php(384): OAuth2\Controller\AuthorizeController->handleAuthorizeRequest() #7 /var/www/html/authorize1.php(25): OAuth2\Server->handleAuthorizeRequest() #8 {main} thrown in /var/www/html/oauth2-server-php/src/OAuth2/Storage/Pdo.php on line 292

**Comment by zengzhi88** [comment]
code_challenge        VARCHAR(1000),
  code_challenge_method VARCHAR(20),

**Comment by reymarkdivino** [comment]
just need to add new Column

**code_challenge VARCHAR(1000)
code_challenge_method VARCHAR(20)**

in table **oauth_authorization_codes**
