### ISSUE TITLE
Reducing sizeof JWT token?

### ISSUE THREAD

**Issue by mtangoo** [bshaffer/oauth2-server-php#687]
I found that sample token is 658chars. That's super big. I use RS256 as algo.
Is there a way to reduce the size? The size does not fit into the table column access_token!

Here is a full error stack if it can help:

```php
{
  "name": "Exception",
  "message": "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'access_token' at row 1",
  "code": "22001",
  "type": "PDOException",
  "file": "/home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php",
  "line": 156,
  "stack-trace": [
    "#0 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php(156): PDOStatement->execute(Array)",
    "#1 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/ResponseType/JwtAccessToken.php(88): OAuth2\\Storage\\Pdo->setAccessToken('eyJ0eXAiOiJKV1Q...', 'testclient', 1, 1451247123, 'default')",
    "#2 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/GrantType/UserCredentials.php(81): OAuth2\\ResponseType\\JwtAccessToken->createAccessToken('testclient', 1, 'default')",
    "#3 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Controller/TokenController.php(201): OAuth2\\GrantType\\UserCredentials->createAccessToken(Object(OAuth2\\ResponseType\\JwtAccessToken), 'testclient', 1, 'default')",
    "#4 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Controller/TokenController.php(49): OAuth2\\Controller\\TokenController->grantAccessToken(Object(filsh\\yii2\\oauth2server\\Request), Object(OAuth2\\Response))",
    "#5 /home/stefano/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php(259): OAuth2\\Controller\\TokenController->handleTokenRequest(Object(filsh\\yii2\\oauth2server\\Request), Object(OAuth2\\Response))",
    "#6 /home/stefano/api/vendor/filsh/yii2-oauth2-server/Server.php(39): OAuth2\\Server->handleTokenRequest(Object(filsh\\yii2\\oauth2server\\Request), NULL)",
    "#7 /home/stefano/api/vendor/filsh/yii2-oauth2-server/controllers/RestController.php(25): filsh\\yii2\\oauth2server\\Server->handleTokenRequest()",
    "#8 [internal function]: filsh\\yii2\\oauth2server\\controllers\\RestController->actionToken()",
    "#9 /home/stefano/api/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)",
    "#10 /home/stefano/api/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)",
    "#11 /home/stefano/api/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('token', Array)",
    "#12 /home/stefano/api/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('oauth2/rest/tok...', Array)",
    "#13 /home/stefano/api/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
    "#14 /home/stefano/api/web/index.php(12): yii\\base\\Application->run()",
    "#15 {main}"
  ]
}

```

**Comment by mtangoo** [comment]
bump;
What do I do to use JWT since they cannot fit the database table field? how do you use it guys?

**Comment by bshaffer** [comment]
You don't need to put a JWT in a database field. You use the signature to
validate it, and then read the data straight out of the payload.

**Comment by mtangoo** [comment]
Thanks, how do I avoid that? AFAIK it the library stores everything in database. Also I don't see anyway to add my payload easily (may be there is a class I have to define them?)

Thanks for your time

**Comment by bshaffer** [comment]
If you're talking about issuing JWT Access Tokens, by default they are [not stored in any database](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L87). 

As far as making a custom payload, override the [`JwtAccessToken::encodeToken`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L117) method.

**Comment by mtangoo** [comment]
Thanks. I will check on the Yii module I use to see why it tries to store the JWT
Thank you!

**Comment by mtangoo** [comment]
Erroneous re-opening
